/********** ADD **********/
export const ADD_PAYMENT = '[PAYMENT] ADD_PAYMENT';
export const ADD_PAYMENT_FAIL = '[PAYMENT] ADD_PAYMENT_FAILS';
export const ADD_PAYMENT_SUCCESS = '[PAYMENT] ADD_PAYMENT_SUCCESS';
/********** GET ALL **********/
export const GET_ALL_PAYMENTS = '[PAYMENT] GET_ALL_PAYMENTS';
export const GET_ALL_PAYMENTS_FAIL = '[PAYMENT] GET_ALL_PAYMENTS_FAILS';
export const GET_ALL_PAYMENTS_SUCCESS = '[PAYMENT] GET_ALL_PAYMENTS_SUCCESS';
/********** UNSET **********/
export const UNSET_PAYMENTS = '[PAYMENT] UNSET_PAYMENTS';