/********** ADD **********/
export const ADD_CATEGORY = '[CATEGORY] ADD_CATEGORY';
export const ADD_CATEGORY_FAIL = '[CATEGORY] ADD_CATEGORY_FAILS';
export const ADD_CATEGORY_SUCCESS = '[CATEGORY] ADD_CATEGORY_SUCCESS';
/********** DELETE **********/
export const DELETE_CATEGORY = '[CATEGORY] DELETE_CATEGORY';
export const DELETE_CATEGORY_FAIL = '[CATEGORY] DELETE_CATEGORY_FAILS';
export const DELETE_CATEGORY_SUCCESS = '[CATEGORY] DELETE_CATEGORY_SUCCESS';
/********** UPDATE **********/
export const UPDATE_CATEGORY = '[CATEGORY] UPDATE_CATEGORY';
export const UPDATE_CATEGORY_FAIL = '[CATEGORY] UPDATE_CATEGORY_FAILS';
export const UPDATE_CATEGORY_SUCCESS = '[CATEGORY] UPDATE_CATEGORY_SUCCESS';
/********** GET ALL **********/
export const GET_ALL_CATEGORIES = '[CATEGORY] GET_ALL_CATEGORIES';
export const GET_ALL_CATEGORIES_FAIL = '[CATEGORY] GET_ALL_CATEGORIES_FAILS';
export const GET_ALL_CATEGORIES_SUCCESS = '[CATEGORY] GET_ALL_CATEGORIES_SUCCESS';
/********** UNSET **********/
export const UNSET_CATEGORIES = '[CATEGORY] UNSET_CATEGORIES';