/********** LOGIN **********/
export const LOGIN_USER = '[USER] LOGIN_USER';
export const LOGIN_USER_FAIL = '[USER] LOGIN_USER_FAILS';
export const LOGIN_USER_SUCCESS = '[USER] LOGIN_USER_SUCCESS';
/********** REGISTER **********/
export const REGISTER_USER = '[USER] REGISTER_USER';
export const REGISTER_USER_FAIL = '[USER] REGISTER_USER_FAILS';
export const REGISTER_USER_SUCCESS = '[USER] REGISTER_USER_SUCCESS';